### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by eric-wieser** [sphinx-contrib/prettyspecialmethods#1]

**Comment by eric-wieser** [comment]
@Thom1729: what are your thoughts on naming?

* `sphinxcontrib.prettyspecialmethods`
* `sphinxcontrib.pretty_special_methods`
* `sphinxcontrib.prettymagic`
* ...

**Comment by Thom1729** [comment]
I don't have a strong opinion on naming — I'm not especially familiar with Sphinx's conventions. Any of the above seems reasonable.
